# Generated by Django 5.1.2 on 2024-11-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Enter the message for the sale/offer.')),
                ('sale_type', models.CharField(choices=[('discount', 'Discount'), ('special_offer', 'Special Offer'), ('summer_sale', 'Summer Sale'), ('flash_sale', 'Flash Sale'), ('clearance', 'Clearance')], default='discount', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave empty for ongoing sale.', null=True)),
            ],
        ),
    ]
